model:
  base_learning_rate: 5.0e-5
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    # for training only
    # ckpt_path: ./logs/2024-09-18T19-50-36_train_aueeckpoints/last.ckpt
    monitor: "val/rec_loss"
    embed_dim: 4
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 501
        kl_weight: 0
        disc_weight: 0.025
        disc_factor: 1.0

    ddconfig:
      double_z: true
      z_channels: 4
      resolution: 512
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

    image_key: 'gt'


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 6
    wrap: false
    train:
      target: basicsr.data.realesrgan_dataset.RealESRGANDataset
      params:
        # gt_path: ['/mnt/lustre/share/jywang/dataset/DIV8K/train_HR/', '/mnt/lustre/share/jywang/dataset/df2k_ost/GT/']
        # face_gt_path: '/mnt/lustre/share/jywang/dataset/FFHQ/1024/'
        gt_path: ['D:/Vinh/3.Project_working/diffusion/dataset/0_SRDataset/archive/train/DIV2K/DIV2K_train_HR', 'D:/Vinh/3.Project_working/diffusion/dataset/0_SRDataset/archive/train/Flickr2K/', 'D:/Vinh/3.Project_working/diffusion/dataset/0_SRDataset/archive/train/OST/' ]
        # face_gt_path: 'D:/Vinh/3.Project_working/diffusion/dataset/0_SRDataset/FFHQ'
        num_face: 10000
        crop_size: 512
        io_backend:
          type: disk

        blur_kernel_size: 21
        kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
        kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
        sinc_prob: 0.1
        blur_sigma: [0.2, 1.5]
        betag_range: [0.5, 2.0]
        betap_range: [1, 1.5]

        blur_kernel_size2: 11
        kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
        kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
        sinc_prob2: 0.1
        blur_sigma2: [0.2, 1.0]
        betag_range2: [0.5, 2.0]
        betap_range2: [1, 1.5]

        final_sinc_prob: 0.8

        gt_size: 512
        use_hflip: True
        use_rot: False

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 1500
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1500
        max_images: 4
        increase_log_steps: False

  trainer:
    benchmark: True
    max_steps: 800000
    accumulate_grad_batches: 8
